# Generated by Django 4.1.5 on 2023-01-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caffeinecalculatorapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caffeineitem",
            old_name="caffeine_amount_in_ml",
            new_name="caffeine_amount_in_mg",
        ),
    ]
